apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-credentials
  namespace: lakehouse
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "lakehouse-access-key",
              "secretKey": "lakehouse-secret-key"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "ReadAcp",
            "Write",
            "WriteAcp"
          ]
        }
      ]
    }
