apiVersion: v1
kind: Secret
metadata:
  name: nessie-s3-credentials
  namespace: lakehouse
stringData:
  # Key names must match accessKeySecret.awsAccessKeyId/awsSecretAccessKey in nessie/values.yaml
  access-key: "lakehouse-access-key"
  secret-key: "lakehouse-secret-key"
