apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polaris-data
  namespace: lakehouse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
