#!/usr/bin/env bash
# Generates a Trino Helm values overlay for Keycloak JWT authentication.
# Output is written to stdout and passed to `helm upgrade --values`.
#
# Required env vars:
#   KEYCLOAK_URL         — Keycloak base URL
#   KEYCLOAK_REALM       — Keycloak realm name
#   NAMESPACE            — K8s namespace (used to read shared-secret from Secret)
#   ACCESS_CONTROL_RULES — path to the JSON rules file (default: trino/access-control-rules.json)

set -euo pipefail

KEYCLOAK_URL="${KEYCLOAK_URL:?KEYCLOAK_URL is required}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:?KEYCLOAK_REALM is required}"
NAMESPACE="${NAMESPACE:?NAMESPACE is required}"
ACCESS_CONTROL_RULES="${ACCESS_CONTROL_RULES:-trino/access-control-rules.json}"

JWKS_URL="${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs"

# Ensure the internal shared-secret exists in K8s (created once, reused on upgrades).
if ! kubectl get secret trino-internal-shared-secret -n "${NAMESPACE}" >/dev/null 2>&1; then
    GENERATED=$(openssl rand -hex 32)
    kubectl create secret generic trino-internal-shared-secret \
        -n "${NAMESPACE}" \
        --from-literal=shared-secret="${GENERATED}" >/dev/null
fi

SHARED_SECRET=$(kubectl get secret trino-internal-shared-secret \
    -n "${NAMESPACE}" \
    -o jsonpath='{.data.shared-secret}' | base64 -d)

# Indent rules.json by 6 spaces for embedding in the YAML `rules` block.
RULES_INDENTED=$(sed 's/^/      /' "${ACCESS_CONTROL_RULES}")

cat <<EOF
# Trino Keycloak JWT auth — generated by scripts/gen-trino-auth.sh
# Keycloak: ${KEYCLOAK_URL}  realm: ${KEYCLOAK_REALM}

# JWT: Trino fetches public keys from Keycloak's JWKS endpoint and validates
# every incoming Bearer token. preferred_username becomes the Trino session
# user, surfaced in query logs, system.runtime tables, and OpenMetadata lineage.
#
# required-issuer is intentionally omitted: Keycloak reflects the request host
# into the iss claim (KC_PROXY_HEADERS=forwarded), so tokens obtained via
# port-forward (localhost) differ from in-cluster tokens. Signature validation
# via the JWKS endpoint is the security gate.
#
# internal-communication.shared-secret: required when external auth is enabled;
# authenticates coordinator-worker RPC. Value comes from trino-internal-shared-secret K8s Secret.
additionalConfigProperties:
  - "http-server.authentication.type=JWT"
  - "http-server.authentication.jwt.key-file=${JWKS_URL}"
  - "http-server.authentication.jwt.principal-field=preferred_username"
  - "internal-communication.shared-secret=${SHARED_SECRET}"

# File-based access control via the chart-native accessControl block.
# The chart creates a ConfigMap, mounts it at /etc/trino/access-control,
# and writes the correct access-control.config-files property automatically.
accessControl:
  type: configmap
  refreshPeriod: 60s
  configFile: "rules.json"
  rules:
    rules.json: |-
${RULES_INDENTED}
EOF
